/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as legacy from "./legacy";
export type { legacy };
export type { SGLCommon } from "./SGLCommon";
export type { SGLLendingBorrowing } from "./SGLLendingBorrowing";
export type { SGLLiquidation } from "./SGLLiquidation";
export type { SGLStorage } from "./SGLStorage";
export type { Singularity } from "./Singularity";
