/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISendFrom,
  ISendFromInterface,
} from "../../../contracts/interfaces/ISendFrom";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "_dstChainId",
        type: "uint16",
      },
      {
        internalType: "bytes32",
        name: "_toAddress",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "address payable",
            name: "refundAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "zroPaymentAddress",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "adapterParams",
            type: "bytes",
          },
        ],
        internalType: "struct ISendFrom.LzCallParams",
        name: "_callParams",
        type: "tuple",
      },
    ],
    name: "sendFrom",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ISendFrom__factory {
  static readonly abi = _abi;
  static createInterface(): ISendFromInterface {
    return new utils.Interface(_abi) as ISendFromInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISendFrom {
    return new Contract(address, _abi, signerOrProvider) as ISendFrom;
  }
}
