/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1155 } from "./IERC1155";
export type { IERC1155TokenReceiver } from "./IERC1155TokenReceiver";
export type { IERC165 } from "./IERC165";
export type { IERC20 } from "./IERC20";
export type { IMasterContract } from "./IMasterContract";
