/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IPenrose {
  export type MasterContractStruct = {
    location: PromiseOrValue<string>;
    risk: PromiseOrValue<BigNumberish>;
  };

  export type MasterContractStructOutput = [string, number] & {
    location: string;
    risk: number;
  };

  export type SwapDataStruct = { minAssetAmount: PromiseOrValue<BigNumberish> };

  export type SwapDataStructOutput = [BigNumber] & {
    minAssetAmount: BigNumber;
  };
}

export interface PenroseInterface extends utils.Interface {
  functions: {
    "_getMasterContractLength((address,uint8)[])": FunctionFragment;
    "bigBangEthDebtRate()": FunctionFragment;
    "bigBangEthMarket()": FunctionFragment;
    "bigBangMarkets()": FunctionFragment;
    "bigBangMasterContractLength()": FunctionFragment;
    "bigbangMasterContracts(uint256)": FunctionFragment;
    "claimOwnership()": FunctionFragment;
    "clonesOf(address,uint256)": FunctionFragment;
    "clonesOfCount(address)": FunctionFragment;
    "conservator()": FunctionFragment;
    "deploy(address,bytes,bool)": FunctionFragment;
    "emptyStrategies(address)": FunctionFragment;
    "executeMarketFn(address[],bytes[],bool)": FunctionFragment;
    "feeTo()": FunctionFragment;
    "masterContractOf(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "paused()": FunctionFragment;
    "pendingOwner()": FunctionFragment;
    "registerBigBang(address,bytes,bool)": FunctionFragment;
    "registerBigBangMasterContract(address,uint8)": FunctionFragment;
    "registerSingularity(address,bytes,bool)": FunctionFragment;
    "registerSingularityMasterContract(address,uint8)": FunctionFragment;
    "setBigBangEthMarket(address)": FunctionFragment;
    "setBigBangEthMarketDebtRate(uint256)": FunctionFragment;
    "setConservator(address)": FunctionFragment;
    "setFeeTo(address)": FunctionFragment;
    "setSwapper(address,bool)": FunctionFragment;
    "setUsdoToken(address)": FunctionFragment;
    "singularityMarkets()": FunctionFragment;
    "singularityMasterContractLength()": FunctionFragment;
    "singularityMasterContracts(uint256)": FunctionFragment;
    "swappers(address)": FunctionFragment;
    "tapAssetId()": FunctionFragment;
    "tapToken()": FunctionFragment;
    "transferOwnership(address,bool,bool)": FunctionFragment;
    "updatePause(bool)": FunctionFragment;
    "usdoAssetId()": FunctionFragment;
    "usdoToken()": FunctionFragment;
    "wethAssetId()": FunctionFragment;
    "wethToken()": FunctionFragment;
    "withdrawAllBigBangFees(address[],address[],(uint256)[])": FunctionFragment;
    "withdrawAllSingularityFees(address[],address[],(uint256)[])": FunctionFragment;
    "yieldBox()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_getMasterContractLength"
      | "bigBangEthDebtRate"
      | "bigBangEthMarket"
      | "bigBangMarkets"
      | "bigBangMasterContractLength"
      | "bigbangMasterContracts"
      | "claimOwnership"
      | "clonesOf"
      | "clonesOfCount"
      | "conservator"
      | "deploy"
      | "emptyStrategies"
      | "executeMarketFn"
      | "feeTo"
      | "masterContractOf"
      | "owner"
      | "paused"
      | "pendingOwner"
      | "registerBigBang"
      | "registerBigBangMasterContract"
      | "registerSingularity"
      | "registerSingularityMasterContract"
      | "setBigBangEthMarket"
      | "setBigBangEthMarketDebtRate"
      | "setConservator"
      | "setFeeTo"
      | "setSwapper"
      | "setUsdoToken"
      | "singularityMarkets"
      | "singularityMasterContractLength"
      | "singularityMasterContracts"
      | "swappers"
      | "tapAssetId"
      | "tapToken"
      | "transferOwnership"
      | "updatePause"
      | "usdoAssetId"
      | "usdoToken"
      | "wethAssetId"
      | "wethToken"
      | "withdrawAllBigBangFees"
      | "withdrawAllSingularityFees"
      | "yieldBox"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_getMasterContractLength",
    values: [IPenrose.MasterContractStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "bigBangEthDebtRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bigBangEthMarket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bigBangMarkets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bigBangMasterContractLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bigbangMasterContracts",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "clonesOf",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "clonesOfCount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "conservator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deploy",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emptyStrategies",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "executeMarketFn",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(functionFragment: "feeTo", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "masterContractOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerBigBang",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerBigBangMasterContract",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSingularity",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSingularityMasterContract",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setBigBangEthMarket",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setBigBangEthMarketDebtRate",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setConservator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeTo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setSwapper",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setUsdoToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "singularityMarkets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "singularityMasterContractLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "singularityMasterContracts",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "swappers",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "tapAssetId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tapToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePause",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "usdoAssetId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdoToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "wethAssetId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "wethToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawAllBigBangFees",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      IPenrose.SwapDataStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAllSingularityFees",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      IPenrose.SwapDataStruct[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "yieldBox", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "_getMasterContractLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bigBangEthDebtRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bigBangEthMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bigBangMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bigBangMasterContractLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bigbangMasterContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "clonesOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "clonesOfCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conservator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emptyStrategies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMarketFn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "masterContractOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerBigBang",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerBigBangMasterContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSingularity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSingularityMasterContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBigBangEthMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBigBangEthMarketDebtRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setConservator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFeeTo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setSwapper", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setUsdoToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "singularityMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "singularityMasterContractLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "singularityMasterContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swappers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tapAssetId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tapToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usdoAssetId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdoToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wethAssetId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wethToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAllBigBangFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAllSingularityFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "yieldBox", data: BytesLike): Result;

  events: {
    "BigBangEthMarketDebtRate(uint256)": EventFragment;
    "BigBangEthMarketSet(address)": EventFragment;
    "ConservatorUpdated(address,address)": EventFragment;
    "FeeToUpdate(address)": EventFragment;
    "FeeVeTapUpdate(address)": EventFragment;
    "LogDeploy(address,bytes,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PausedUpdated(bool,bool)": EventFragment;
    "ProtocolWithdrawal(address[],uint256)": EventFragment;
    "RegisterBigBang(address,address)": EventFragment;
    "RegisterBigBangMasterContract(address,uint8)": EventFragment;
    "RegisterSingularity(address,address)": EventFragment;
    "RegisterSingularityMasterContract(address,uint8)": EventFragment;
    "SwapperUpdate(address,bool)": EventFragment;
    "UsdoTokenUpdated(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BigBangEthMarketDebtRate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BigBangEthMarketSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConservatorUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeeToUpdate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeeVeTapUpdate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogDeploy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PausedUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProtocolWithdrawal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RegisterBigBang"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "RegisterBigBangMasterContract"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RegisterSingularity"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "RegisterSingularityMasterContract"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapperUpdate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UsdoTokenUpdated"): EventFragment;
}

export interface BigBangEthMarketDebtRateEventObject {
  _rate: BigNumber;
}
export type BigBangEthMarketDebtRateEvent = TypedEvent<
  [BigNumber],
  BigBangEthMarketDebtRateEventObject
>;

export type BigBangEthMarketDebtRateEventFilter =
  TypedEventFilter<BigBangEthMarketDebtRateEvent>;

export interface BigBangEthMarketSetEventObject {
  _newAddress: string;
}
export type BigBangEthMarketSetEvent = TypedEvent<
  [string],
  BigBangEthMarketSetEventObject
>;

export type BigBangEthMarketSetEventFilter =
  TypedEventFilter<BigBangEthMarketSetEvent>;

export interface ConservatorUpdatedEventObject {
  old: string;
  _new: string;
}
export type ConservatorUpdatedEvent = TypedEvent<
  [string, string],
  ConservatorUpdatedEventObject
>;

export type ConservatorUpdatedEventFilter =
  TypedEventFilter<ConservatorUpdatedEvent>;

export interface FeeToUpdateEventObject {
  newFeeTo: string;
}
export type FeeToUpdateEvent = TypedEvent<[string], FeeToUpdateEventObject>;

export type FeeToUpdateEventFilter = TypedEventFilter<FeeToUpdateEvent>;

export interface FeeVeTapUpdateEventObject {
  newFeeVeTap: string;
}
export type FeeVeTapUpdateEvent = TypedEvent<
  [string],
  FeeVeTapUpdateEventObject
>;

export type FeeVeTapUpdateEventFilter = TypedEventFilter<FeeVeTapUpdateEvent>;

export interface LogDeployEventObject {
  masterContract: string;
  data: string;
  cloneAddress: string;
}
export type LogDeployEvent = TypedEvent<
  [string, string, string],
  LogDeployEventObject
>;

export type LogDeployEventFilter = TypedEventFilter<LogDeployEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedUpdatedEventObject {
  oldState: boolean;
  newState: boolean;
}
export type PausedUpdatedEvent = TypedEvent<
  [boolean, boolean],
  PausedUpdatedEventObject
>;

export type PausedUpdatedEventFilter = TypedEventFilter<PausedUpdatedEvent>;

export interface ProtocolWithdrawalEventObject {
  markets: string[];
  timestamp: BigNumber;
}
export type ProtocolWithdrawalEvent = TypedEvent<
  [string[], BigNumber],
  ProtocolWithdrawalEventObject
>;

export type ProtocolWithdrawalEventFilter =
  TypedEventFilter<ProtocolWithdrawalEvent>;

export interface RegisterBigBangEventObject {
  location: string;
  masterContract: string;
}
export type RegisterBigBangEvent = TypedEvent<
  [string, string],
  RegisterBigBangEventObject
>;

export type RegisterBigBangEventFilter = TypedEventFilter<RegisterBigBangEvent>;

export interface RegisterBigBangMasterContractEventObject {
  location: string;
  risk: number;
}
export type RegisterBigBangMasterContractEvent = TypedEvent<
  [string, number],
  RegisterBigBangMasterContractEventObject
>;

export type RegisterBigBangMasterContractEventFilter =
  TypedEventFilter<RegisterBigBangMasterContractEvent>;

export interface RegisterSingularityEventObject {
  location: string;
  masterContract: string;
}
export type RegisterSingularityEvent = TypedEvent<
  [string, string],
  RegisterSingularityEventObject
>;

export type RegisterSingularityEventFilter =
  TypedEventFilter<RegisterSingularityEvent>;

export interface RegisterSingularityMasterContractEventObject {
  location: string;
  risk: number;
}
export type RegisterSingularityMasterContractEvent = TypedEvent<
  [string, number],
  RegisterSingularityMasterContractEventObject
>;

export type RegisterSingularityMasterContractEventFilter =
  TypedEventFilter<RegisterSingularityMasterContractEvent>;

export interface SwapperUpdateEventObject {
  swapper: string;
  isRegistered: boolean;
}
export type SwapperUpdateEvent = TypedEvent<
  [string, boolean],
  SwapperUpdateEventObject
>;

export type SwapperUpdateEventFilter = TypedEventFilter<SwapperUpdateEvent>;

export interface UsdoTokenUpdatedEventObject {
  usdoToken: string;
  assetId: BigNumber;
}
export type UsdoTokenUpdatedEvent = TypedEvent<
  [string, BigNumber],
  UsdoTokenUpdatedEventObject
>;

export type UsdoTokenUpdatedEventFilter =
  TypedEventFilter<UsdoTokenUpdatedEvent>;

export interface Penrose extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PenroseInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _getMasterContractLength(
      array: IPenrose.MasterContractStruct[],
      overrides?: CallOverrides
    ): Promise<[string[]] & { markets: string[] }>;

    bigBangEthDebtRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    bigBangEthMarket(overrides?: CallOverrides): Promise<[string]>;

    bigBangMarkets(
      overrides?: CallOverrides
    ): Promise<[string[]] & { markets: string[] }>;

    bigBangMasterContractLength(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    bigbangMasterContracts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, number] & { location: string; risk: number }>;

    claimOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    clonesOf(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    clonesOfCount(
      masterContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { cloneCount: BigNumber }>;

    conservator(overrides?: CallOverrides): Promise<[string]>;

    deploy(
      masterContract: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      useCreate2: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    emptyStrategies(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    executeMarketFn(
      mc: PromiseOrValue<string>[],
      data: PromiseOrValue<BytesLike>[],
      forceSuccess: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    feeTo(overrides?: CallOverrides): Promise<[string]>;

    masterContractOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    pendingOwner(overrides?: CallOverrides): Promise<[string]>;

    registerBigBang(
      mc: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      useCreate2: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerBigBangMasterContract(
      mcAddress: PromiseOrValue<string>,
      contractType_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerSingularity(
      mc: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      useCreate2: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerSingularityMasterContract(
      mcAddress: PromiseOrValue<string>,
      contractType_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setBigBangEthMarket(
      _market: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setBigBangEthMarketDebtRate(
      _rate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setConservator(
      _conservator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFeeTo(
      feeTo_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setSwapper(
      swapper: PromiseOrValue<string>,
      enable: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setUsdoToken(
      _usdoToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    singularityMarkets(
      overrides?: CallOverrides
    ): Promise<[string[]] & { markets: string[] }>;

    singularityMasterContractLength(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    singularityMasterContracts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, number] & { location: string; risk: number }>;

    swappers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    tapAssetId(overrides?: CallOverrides): Promise<[BigNumber]>;

    tapToken(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      direct: PromiseOrValue<boolean>,
      renounce: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updatePause(
      val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    usdoAssetId(overrides?: CallOverrides): Promise<[BigNumber]>;

    usdoToken(overrides?: CallOverrides): Promise<[string]>;

    wethAssetId(overrides?: CallOverrides): Promise<[BigNumber]>;

    wethToken(overrides?: CallOverrides): Promise<[string]>;

    withdrawAllBigBangFees(
      markets_: PromiseOrValue<string>[],
      swappers_: PromiseOrValue<string>[],
      swapData_: IPenrose.SwapDataStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawAllSingularityFees(
      markets_: PromiseOrValue<string>[],
      swappers_: PromiseOrValue<string>[],
      swapData_: IPenrose.SwapDataStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    yieldBox(overrides?: CallOverrides): Promise<[string]>;
  };

  _getMasterContractLength(
    array: IPenrose.MasterContractStruct[],
    overrides?: CallOverrides
  ): Promise<string[]>;

  bigBangEthDebtRate(overrides?: CallOverrides): Promise<BigNumber>;

  bigBangEthMarket(overrides?: CallOverrides): Promise<string>;

  bigBangMarkets(overrides?: CallOverrides): Promise<string[]>;

  bigBangMasterContractLength(overrides?: CallOverrides): Promise<BigNumber>;

  bigbangMasterContracts(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, number] & { location: string; risk: number }>;

  claimOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  clonesOf(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  clonesOfCount(
    masterContract: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  conservator(overrides?: CallOverrides): Promise<string>;

  deploy(
    masterContract: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    useCreate2: PromiseOrValue<boolean>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  emptyStrategies(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  executeMarketFn(
    mc: PromiseOrValue<string>[],
    data: PromiseOrValue<BytesLike>[],
    forceSuccess: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  feeTo(overrides?: CallOverrides): Promise<string>;

  masterContractOf(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  pendingOwner(overrides?: CallOverrides): Promise<string>;

  registerBigBang(
    mc: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    useCreate2: PromiseOrValue<boolean>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerBigBangMasterContract(
    mcAddress: PromiseOrValue<string>,
    contractType_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerSingularity(
    mc: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    useCreate2: PromiseOrValue<boolean>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerSingularityMasterContract(
    mcAddress: PromiseOrValue<string>,
    contractType_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setBigBangEthMarket(
    _market: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setBigBangEthMarketDebtRate(
    _rate: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setConservator(
    _conservator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFeeTo(
    feeTo_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setSwapper(
    swapper: PromiseOrValue<string>,
    enable: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setUsdoToken(
    _usdoToken: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  singularityMarkets(overrides?: CallOverrides): Promise<string[]>;

  singularityMasterContractLength(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  singularityMasterContracts(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, number] & { location: string; risk: number }>;

  swappers(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  tapAssetId(overrides?: CallOverrides): Promise<BigNumber>;

  tapToken(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    direct: PromiseOrValue<boolean>,
    renounce: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updatePause(
    val: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  usdoAssetId(overrides?: CallOverrides): Promise<BigNumber>;

  usdoToken(overrides?: CallOverrides): Promise<string>;

  wethAssetId(overrides?: CallOverrides): Promise<BigNumber>;

  wethToken(overrides?: CallOverrides): Promise<string>;

  withdrawAllBigBangFees(
    markets_: PromiseOrValue<string>[],
    swappers_: PromiseOrValue<string>[],
    swapData_: IPenrose.SwapDataStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawAllSingularityFees(
    markets_: PromiseOrValue<string>[],
    swappers_: PromiseOrValue<string>[],
    swapData_: IPenrose.SwapDataStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  yieldBox(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    _getMasterContractLength(
      array: IPenrose.MasterContractStruct[],
      overrides?: CallOverrides
    ): Promise<string[]>;

    bigBangEthDebtRate(overrides?: CallOverrides): Promise<BigNumber>;

    bigBangEthMarket(overrides?: CallOverrides): Promise<string>;

    bigBangMarkets(overrides?: CallOverrides): Promise<string[]>;

    bigBangMasterContractLength(overrides?: CallOverrides): Promise<BigNumber>;

    bigbangMasterContracts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, number] & { location: string; risk: number }>;

    claimOwnership(overrides?: CallOverrides): Promise<void>;

    clonesOf(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    clonesOfCount(
      masterContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    conservator(overrides?: CallOverrides): Promise<string>;

    deploy(
      masterContract: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      useCreate2: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<string>;

    emptyStrategies(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    executeMarketFn(
      mc: PromiseOrValue<string>[],
      data: PromiseOrValue<BytesLike>[],
      forceSuccess: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<
      [boolean[], string[]] & { success: boolean[]; result: string[] }
    >;

    feeTo(overrides?: CallOverrides): Promise<string>;

    masterContractOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    pendingOwner(overrides?: CallOverrides): Promise<string>;

    registerBigBang(
      mc: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      useCreate2: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<string>;

    registerBigBangMasterContract(
      mcAddress: PromiseOrValue<string>,
      contractType_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerSingularity(
      mc: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      useCreate2: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<string>;

    registerSingularityMasterContract(
      mcAddress: PromiseOrValue<string>,
      contractType_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setBigBangEthMarket(
      _market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setBigBangEthMarketDebtRate(
      _rate: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setConservator(
      _conservator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeeTo(
      feeTo_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setSwapper(
      swapper: PromiseOrValue<string>,
      enable: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setUsdoToken(
      _usdoToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    singularityMarkets(overrides?: CallOverrides): Promise<string[]>;

    singularityMasterContractLength(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    singularityMasterContracts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, number] & { location: string; risk: number }>;

    swappers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    tapAssetId(overrides?: CallOverrides): Promise<BigNumber>;

    tapToken(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      direct: PromiseOrValue<boolean>,
      renounce: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    updatePause(
      val: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    usdoAssetId(overrides?: CallOverrides): Promise<BigNumber>;

    usdoToken(overrides?: CallOverrides): Promise<string>;

    wethAssetId(overrides?: CallOverrides): Promise<BigNumber>;

    wethToken(overrides?: CallOverrides): Promise<string>;

    withdrawAllBigBangFees(
      markets_: PromiseOrValue<string>[],
      swappers_: PromiseOrValue<string>[],
      swapData_: IPenrose.SwapDataStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawAllSingularityFees(
      markets_: PromiseOrValue<string>[],
      swappers_: PromiseOrValue<string>[],
      swapData_: IPenrose.SwapDataStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    yieldBox(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "BigBangEthMarketDebtRate(uint256)"(
      _rate?: null
    ): BigBangEthMarketDebtRateEventFilter;
    BigBangEthMarketDebtRate(_rate?: null): BigBangEthMarketDebtRateEventFilter;

    "BigBangEthMarketSet(address)"(
      _newAddress?: PromiseOrValue<string> | null
    ): BigBangEthMarketSetEventFilter;
    BigBangEthMarketSet(
      _newAddress?: PromiseOrValue<string> | null
    ): BigBangEthMarketSetEventFilter;

    "ConservatorUpdated(address,address)"(
      old?: PromiseOrValue<string> | null,
      _new?: PromiseOrValue<string> | null
    ): ConservatorUpdatedEventFilter;
    ConservatorUpdated(
      old?: PromiseOrValue<string> | null,
      _new?: PromiseOrValue<string> | null
    ): ConservatorUpdatedEventFilter;

    "FeeToUpdate(address)"(newFeeTo?: null): FeeToUpdateEventFilter;
    FeeToUpdate(newFeeTo?: null): FeeToUpdateEventFilter;

    "FeeVeTapUpdate(address)"(newFeeVeTap?: null): FeeVeTapUpdateEventFilter;
    FeeVeTapUpdate(newFeeVeTap?: null): FeeVeTapUpdateEventFilter;

    "LogDeploy(address,bytes,address)"(
      masterContract?: PromiseOrValue<string> | null,
      data?: null,
      cloneAddress?: PromiseOrValue<string> | null
    ): LogDeployEventFilter;
    LogDeploy(
      masterContract?: PromiseOrValue<string> | null,
      data?: null,
      cloneAddress?: PromiseOrValue<string> | null
    ): LogDeployEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "PausedUpdated(bool,bool)"(
      oldState?: null,
      newState?: null
    ): PausedUpdatedEventFilter;
    PausedUpdated(oldState?: null, newState?: null): PausedUpdatedEventFilter;

    "ProtocolWithdrawal(address[],uint256)"(
      markets?: null,
      timestamp?: null
    ): ProtocolWithdrawalEventFilter;
    ProtocolWithdrawal(
      markets?: null,
      timestamp?: null
    ): ProtocolWithdrawalEventFilter;

    "RegisterBigBang(address,address)"(
      location?: null,
      masterContract?: null
    ): RegisterBigBangEventFilter;
    RegisterBigBang(
      location?: null,
      masterContract?: null
    ): RegisterBigBangEventFilter;

    "RegisterBigBangMasterContract(address,uint8)"(
      location?: null,
      risk?: null
    ): RegisterBigBangMasterContractEventFilter;
    RegisterBigBangMasterContract(
      location?: null,
      risk?: null
    ): RegisterBigBangMasterContractEventFilter;

    "RegisterSingularity(address,address)"(
      location?: null,
      masterContract?: null
    ): RegisterSingularityEventFilter;
    RegisterSingularity(
      location?: null,
      masterContract?: null
    ): RegisterSingularityEventFilter;

    "RegisterSingularityMasterContract(address,uint8)"(
      location?: null,
      risk?: null
    ): RegisterSingularityMasterContractEventFilter;
    RegisterSingularityMasterContract(
      location?: null,
      risk?: null
    ): RegisterSingularityMasterContractEventFilter;

    "SwapperUpdate(address,bool)"(
      swapper?: null,
      isRegistered?: null
    ): SwapperUpdateEventFilter;
    SwapperUpdate(
      swapper?: null,
      isRegistered?: null
    ): SwapperUpdateEventFilter;

    "UsdoTokenUpdated(address,uint256)"(
      usdoToken?: PromiseOrValue<string> | null,
      assetId?: null
    ): UsdoTokenUpdatedEventFilter;
    UsdoTokenUpdated(
      usdoToken?: PromiseOrValue<string> | null,
      assetId?: null
    ): UsdoTokenUpdatedEventFilter;
  };

  estimateGas: {
    _getMasterContractLength(
      array: IPenrose.MasterContractStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bigBangEthDebtRate(overrides?: CallOverrides): Promise<BigNumber>;

    bigBangEthMarket(overrides?: CallOverrides): Promise<BigNumber>;

    bigBangMarkets(overrides?: CallOverrides): Promise<BigNumber>;

    bigBangMasterContractLength(overrides?: CallOverrides): Promise<BigNumber>;

    bigbangMasterContracts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    clonesOf(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    clonesOfCount(
      masterContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    conservator(overrides?: CallOverrides): Promise<BigNumber>;

    deploy(
      masterContract: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      useCreate2: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    emptyStrategies(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    executeMarketFn(
      mc: PromiseOrValue<string>[],
      data: PromiseOrValue<BytesLike>[],
      forceSuccess: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    feeTo(overrides?: CallOverrides): Promise<BigNumber>;

    masterContractOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    pendingOwner(overrides?: CallOverrides): Promise<BigNumber>;

    registerBigBang(
      mc: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      useCreate2: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerBigBangMasterContract(
      mcAddress: PromiseOrValue<string>,
      contractType_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerSingularity(
      mc: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      useCreate2: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerSingularityMasterContract(
      mcAddress: PromiseOrValue<string>,
      contractType_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setBigBangEthMarket(
      _market: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setBigBangEthMarketDebtRate(
      _rate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setConservator(
      _conservator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFeeTo(
      feeTo_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setSwapper(
      swapper: PromiseOrValue<string>,
      enable: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setUsdoToken(
      _usdoToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    singularityMarkets(overrides?: CallOverrides): Promise<BigNumber>;

    singularityMasterContractLength(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    singularityMasterContracts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swappers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tapAssetId(overrides?: CallOverrides): Promise<BigNumber>;

    tapToken(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      direct: PromiseOrValue<boolean>,
      renounce: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updatePause(
      val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    usdoAssetId(overrides?: CallOverrides): Promise<BigNumber>;

    usdoToken(overrides?: CallOverrides): Promise<BigNumber>;

    wethAssetId(overrides?: CallOverrides): Promise<BigNumber>;

    wethToken(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawAllBigBangFees(
      markets_: PromiseOrValue<string>[],
      swappers_: PromiseOrValue<string>[],
      swapData_: IPenrose.SwapDataStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawAllSingularityFees(
      markets_: PromiseOrValue<string>[],
      swappers_: PromiseOrValue<string>[],
      swapData_: IPenrose.SwapDataStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    yieldBox(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _getMasterContractLength(
      array: IPenrose.MasterContractStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bigBangEthDebtRate(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bigBangEthMarket(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bigBangMarkets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bigBangMasterContractLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bigbangMasterContracts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    clonesOf(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    clonesOfCount(
      masterContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    conservator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deploy(
      masterContract: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      useCreate2: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    emptyStrategies(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    executeMarketFn(
      mc: PromiseOrValue<string>[],
      data: PromiseOrValue<BytesLike>[],
      forceSuccess: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    feeTo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    masterContractOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerBigBang(
      mc: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      useCreate2: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerBigBangMasterContract(
      mcAddress: PromiseOrValue<string>,
      contractType_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerSingularity(
      mc: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      useCreate2: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerSingularityMasterContract(
      mcAddress: PromiseOrValue<string>,
      contractType_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setBigBangEthMarket(
      _market: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setBigBangEthMarketDebtRate(
      _rate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setConservator(
      _conservator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFeeTo(
      feeTo_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setSwapper(
      swapper: PromiseOrValue<string>,
      enable: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setUsdoToken(
      _usdoToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    singularityMarkets(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    singularityMasterContractLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    singularityMasterContracts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swappers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tapAssetId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tapToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      direct: PromiseOrValue<boolean>,
      renounce: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updatePause(
      val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    usdoAssetId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    usdoToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wethAssetId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wethToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawAllBigBangFees(
      markets_: PromiseOrValue<string>[],
      swappers_: PromiseOrValue<string>[],
      swapData_: IPenrose.SwapDataStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawAllSingularityFees(
      markets_: PromiseOrValue<string>[],
      swappers_: PromiseOrValue<string>[],
      swapData_: IPenrose.SwapDataStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    yieldBox(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
