/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CurveStableToUsdoBidder } from "./CurveStableToUsdoBidder";
export type { IBidder } from "./IBidder";
export type { UniUsdoToWethBidder } from "./UniUsdoToWethBidder";
