/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as flashLoanMockSol from "./FlashLoanMock.sol";
export type { flashLoanMockSol };
export type { VulnMultiSwapper } from "./VulnMultiSwapper";
