/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface ERC20FactoryMockInterface extends utils.Interface {
  functions: {
    "deployToken(uint256,uint8,uint256)": FunctionFragment;
    "last()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "deployToken" | "last"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployToken",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "last", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "deployToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "last", data: BytesLike): Result;

  events: {};
}

export interface ERC20FactoryMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ERC20FactoryMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployToken(
      _supply: PromiseOrValue<BigNumberish>,
      _decimals: PromiseOrValue<BigNumberish>,
      _mintLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    last(overrides?: CallOverrides): Promise<[string]>;
  };

  deployToken(
    _supply: PromiseOrValue<BigNumberish>,
    _decimals: PromiseOrValue<BigNumberish>,
    _mintLimit: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  last(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    deployToken(
      _supply: PromiseOrValue<BigNumberish>,
      _decimals: PromiseOrValue<BigNumberish>,
      _mintLimit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    last(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    deployToken(
      _supply: PromiseOrValue<BigNumberish>,
      _decimals: PromiseOrValue<BigNumberish>,
      _mintLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    last(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    deployToken(
      _supply: PromiseOrValue<BigNumberish>,
      _decimals: PromiseOrValue<BigNumberish>,
      _mintLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    last(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
