/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20FactoryMock } from "./ERC20FactoryMock";
export type { ERC20Mock } from "./ERC20Mock";
export type { OracleMock } from "./OracleMock";
export type { WETH9Mock } from "./WETH9Mock";
