import { EChainID } from '@tapioca-sdk/api/config';

// Name of the contract deployments to be used in the deployment scripts and saved in the deployments file
export const DEPLOYMENT_NAMES = {
    PENROSE: 'PENROSE',
    USDO: 'USDO',
    USDO_EXT_EXEC: 'USDO_EXT_EXEC',
    USDO_FLASHLOAN_HELPER: 'USDO_FLASHLOAN_HELPER',
    SIMPLE_LEVERAGE_EXECUTOR: 'SIMPLE_LEVERAGE_EXECUTOR',
    // SGL
    SGL_MEDIUM_RISK_MC: 'SGL_MEDIUM_RISK_MC',
    SGL_LIQUIDATION_MODULE: 'SGL_LIQUIDATION_MODULE',
    SGL_BORROW_MODULE: 'SGL_BORROW_MODULE',
    SGL_COLLATERAL_MODULE: 'SGL_COLLATERAL_MODULE',
    SGL_LEVERAGE_MODULE: 'SGL_LEVERAGE_MODULE',
    // BB
    BB_MEDIUM_RISK_MC: 'BB_MEDIUM_RISK_MC',
    BB_LIQUIDATION_MODULE: 'BB_LIQUIDATION_MODULE',
    BB_BORROW_MODULE: 'BB_BORROW_MODULE',
    BB_COLLATERAL_MODULE: 'BB_COLLATERAL_MODULE',
    BB_LEVERAGE_MODULE: 'BB_LEVERAGE_MODULE',
    // USDO
    USDO_SENDER_MODULE: 'USDO_SENDER_MODULE',
    USDO_RECEIVER_MODULE: 'USDO_RECEIVER_MODULE',
    USDO_MARKET_RECEIVER_MODULE: 'USDO_MARKET_RECEIVER_MODULE',
    USDO_OPTION_RECEIVER_MODULE: 'USDO_OPTION_RECEIVER_MODULE',
};

type TPostLbp = {};

const POST_LBP: TPostLbp = {};
POST_LBP['31337' as EChainID] = POST_LBP[EChainID.ARBITRUM]; // Copy from Arbitrum

type TMisc = {
    [key in EChainID]?: {
        WETH: string;
    };
};
const MISC: TMisc = {
    [EChainID.ARBITRUM]: {
        WETH: '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1',
    },
    [EChainID.MAINNET]: {
        WETH: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
    },
    [EChainID.ARBITRUM_SEPOLIA]: {
        WETH: '0x2EAe4fbc552fE35C1D3Df2B546032409bb0E431E',
    },
    [EChainID.SEPOLIA]: {
        WETH: '0xD8a79b479b0c47675E3882A1DAA494b6775CE227', // Mock deployment
    },
    [EChainID.OPTIMISM_SEPOLIA]: {
        WETH: '0x4fB538Ed1a085200bD08F66083B72c0bfEb29112',
    },
};

export const DEPLOY_CONFIG = {
    POST_LBP,
    MISC,
};
