/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBigBang,
  IBigBangInterface,
} from "../../../../contracts/usd0/interfaces/IBigBang";

const _abi = [
  {
    inputs: [],
    name: "accrueInfo",
    outputs: [
      {
        internalType: "uint64",
        name: "debtRate",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "lastAccrued",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBigBang__factory {
  static readonly abi = _abi;
  static createInterface(): IBigBangInterface {
    return new utils.Interface(_abi) as IBigBangInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBigBang {
    return new Contract(address, _abi, signerOrProvider) as IBigBang;
  }
}
