name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ouzi-dev/commit-status-updater@v1.1.0
      - run: |
          npm install
          yarn test
      - if: always()
        uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          status: "${{ job.status }}"